- name: Prepare system
  hosts: all

  become: yes
  tasks:
    - name: Disabling swap
      command: "{{ item }}"
      with_items:
        - swapoff -a
        - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
        
    - name: Prepare network settings
      script: /home/vagrant/ansible/prepare-system.sh
      
    - name: Apt update and upgrade
      apt:
        update_cache: yes
        force_apt_get: yes
        upgrade: yes